name: CI

on:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  workflow-gpr:
    name: GPR workflow (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: emul
          miniforge-version: latest

      - name: Run GPR workflow
        run: python workflow_gpr.py

  workflow-dsi:
    name: DSI workflow (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: environment.yml
          activate-environment: emul
          miniforge-version: latest

      - name: Run DSI workflow
        run: python workflow_dsi.py
